# Generated by Django 5.0.7 on 2025-06-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_remove_genre_category_alter_genre_options_and_more"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchhistory",
            name="episode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.episode",
            ),
        ),
    ]
