# Generated by Django 5.0.7 on 2025-06-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_watchhistory_episode"),
    ]

    operations = []
