# Generated by Django 5.0.7 on 2025-06-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_add_video_file_field"),
        ("profiles", "0004_watchhistory_unique_watch_history_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchhistory",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
        ),
    ]
