# Generated by Django 5.0.7 on 2025-06-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_add_video_file_field"),
        ("profiles", "0005_alter_watchhistory_movie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mylist",
            unique_together={("profile", "movie")},
        ),
        migrations.AddField(
            model_name="mylist",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[("movie", "Movie"), ("series", "TV Series")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mylist",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="series_in_list",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="mylist",
            name="movie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.movie",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mylist",
            unique_together={("profile", "movie"), ("profile", "series")},
        ),
    ]
