# Generated by Django 5.0.7 on 2025-06-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0007_populate_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mylist",
            name="content_type",
            field=models.CharField(
                choices=[("movie", "Movie"), ("series", "TV Series")],
                default="movie",
                max_length=10,
            ),
        ),
    ]
