# Generated by Django 5.0.7 on 2025-06-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profiles.profile"
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="movies.movie",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="movies.season",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rating",
            unique_together={("movie", "profile")},
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("series", "season_number")},
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("season", "episode_number")},
        ),
    ]
