# Generated by Django 5.0.7 on 2025-06-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this movie is active and should be shown on the site",
            ),
        ),
    ]
