# Generated by Django 5.0.7 on 2025-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="ai_model_used",
            field=models.CharField(
                blank=True,
                help_text="AI model used for generation (e.g., DALL·E, Stable Diffusion)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="content_category",
            field=models.CharField(
                choices=[
                    ("ai_generated", "AI-Generated Movies"),
                    ("ai_upscaled", "AI-Upscaled Classics"),
                    ("user_created", "User Creations"),
                    ("ai_series", "AI-Generated Series"),
                    ("trending", "Trending AI Content"),
                ],
                default="ai_generated",
                help_text="Category of AI content",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="generation_parameters",
            field=models.JSONField(
                blank=True,
                help_text="Parameters used for AI generation (prompts, settings, etc.)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_ai_generated",
            field=models.BooleanField(
                default=True, help_text="Whether this content was generated by AI"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="original_quality",
            field=models.CharField(
                blank=True,
                help_text="Original quality if upscaled (e.g., 480p, 720p)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="upscale_technique",
            field=models.CharField(
                blank=True,
                help_text="Technique used for upscaling (e.g., ESRGAN, Real-ESRGAN)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("series", "TV Series"),
                    ("documentary", "Documentary"),
                    ("short", "Short Film"),
                ],
                default="movie",
                max_length=20,
            ),
        ),
    ]
