# Generated by Django 5.0.7 on 2025-06-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_ai_model_used_movie_content_category_and_more"),
    ]

    operations = []
