# Generated by Django 5.0.7 on 2025-06-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_add_netflix_genres"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenreCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Genre Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="genre",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="genre",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="genres",
                to="movies.genrecategory",
            ),
        ),
    ]
