# Generated by Django 5.0.7 on 2025-06-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_genrecategory_alter_genre_options_genre_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="genre",
            name="order",
        ),
        migrations.DeleteModel(
            name="GenreCategory",
        ),
    ]
