# Generated by Django 5.0.7 on 2025-06-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_subtitle_videofile_videoquality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="subtitles",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="subtitles",
        ),
        migrations.RemoveField(
            model_name="videofile",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="video_files",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="video_files",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="default_quality",
        ),
        migrations.AddField(
            model_name="episode",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="episodes/"),
        ),
        migrations.AddField(
            model_name="episode",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AddField(
            model_name="movie",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Subtitle",
        ),
        migrations.DeleteModel(
            name="VideoFile",
        ),
        migrations.DeleteModel(
            name="VideoQuality",
        ),
    ]
